In [1]:
# !pip install pandas
# !pip install openpyxl

In [2]:
import pandas as pd
import numpy as np
import warnings
from openpyxl import load_workbook

warnings.filterwarnings('ignore')

In [3]:
workbook = load_workbook(filename="GoodBelly-DataSet.xlsx")
# print(workbook.sheetnames)
sheet = workbook['Real Data']
data = sheet.values
df = pd.DataFrame(data)
new_header = df.iloc[0] # Grab the first row for the header
df = df[1:] # Take the data less the header row
df.columns = new_header # Set the header row as the DataFrame header
df = df.loc[:, :'Fitness']
df = df.apply(pd.to_numeric, errors='ignore')
    
df.head()

,Date,Region,Store,Units Sold,Average Retail Price,Sales Rep,Endcap,Demo,Demo1-3,Demo4-5,Natural,Fitness
1,2010-05-04,FL,Biscayne (aka Aventura),150.702088,4.390000,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,2010-05-11,FL,Biscayne (aka Aventura),197.403797,3.997692,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,2010-05-18,FL,Biscayne (aka Aventura),235.106172,3.809231,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,2010-05-25,FL,Biscayne (aka Aventura),226.692427,3.835000,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5,2010-06-01,FL,Biscayne (aka Aventura),257.688151,3.902500,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1386 entries, 1 to 1386
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  1386 non-null   datetime64[ns]
 1   Region                1386 non-null   object
 2   Store                 1386 non-null   object
 3   Units Sold            1386 non-null   float64
 4   Average Retail Price  1386 non-null   float64
 5   Sales Rep             1386 non-null   float64
 6   Endcap                1386 non-null   float64
 7   Demo                  1386 non-null   float64
 8   Demo1-3               1386 non-null   float64
 9   Demo4-5               1386 non-null   float64
 10  Natural               1386 non-null   float64
 11  Fitness               1386 non-null   float64
dtypes: datetime64[ns](1), float64(9), object(2)
memory usage: 130.1+ KB

In [5]:
#Q1 - Give summary of numeric type of columns in dataset?

In [6]:
df.describe()

,Date,Units Sold,Average Retail Price,Sales Rep,Endcap,Demo,Demo1-3,Demo4-5,Natural,Fitness
count,1386,1386.000000,1386.000000,1386.000000,1386.000000,1386.000000,1386.000000,1386.000000,1386.000000,1386.000000
mean,2010-06-08 00:00:00,253.820718,4.107093,0.549784,0.038240,0.058442,0.156566,0.075758,1.448773,2.476190
min,2010-05-04 00:00:00,47.559852,2.889286,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2010-05-18 00:00:00,189.995471,3.775714,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
50%,2010-06-08 00:00:00,236.735266,4.096667,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000
75%,2010-06-29 00:00:00,295.804391,4.425067,1.000000,0.000000,0.000000,0.000000,0.000000,2.000000,4.000000
max,2010-07-13 00:00:00,1041.200256,6.251538,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,5.000000
std,NaN,110.998731,0.463828,0.497695,0.191843,0.234661,0.363522,0.264705,0.975092,1.592789

In [7]:
#Q2 Calc STD of columns in dataset
df.describe().loc[['std'],:]

,Date,Units Sold,Average Retail Price,Sales Rep,Endcap,Demo,Demo1-3,Demo4-5,Natural,Fitness
std,NaN,110.998731,0.463828,0.497695,0.191843,0.234661,0.363522,0.264705,0.975092,1.592789

In [8]:
#Q3 mean of first 50 records in dataset

In [9]:
df_50 = df.head(50)
df_50.describe().loc[['mean'],:]

,Date,Units Sold,Average Retail Price,Sales Rep,Endcap,Demo,Demo1-3,Demo4-5,Natural,Fitness
mean,2010-06-05 21:36:00,186.280727,4.128036,0.0,0.1,0.0,0.0,0.04,1.3,1.56

In [10]:
#Q4 What are thecolumn names

In [11]:
df.columns

Index(['Date', 'Region', 'Store', 'Units Sold', 'Average Retail Price',
       'Sales Rep', 'Endcap', 'Demo', 'Demo1-3', 'Demo4-5', 'Natural',
       'Fitness'],
      dtype='object', name=0)

In [12]:
#Q - Number of elements in dataset

In [13]:
df.shape[0] * df.shape[1]

16632

In [14]:
#Q- No. of records this dataset has

In [15]:
df.shape[0]

1386

In [16]:
#Q type of column dataset has

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1386 entries, 1 to 1386
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  1386 non-null   datetime64[ns]
 1   Region                1386 non-null   object
 2   Store                 1386 non-null   object
 3   Units Sold            1386 non-null   float64
 4   Average Retail Price  1386 non-null   float64
 5   Sales Rep             1386 non-null   float64
 6   Endcap                1386 non-null   float64
 7   Demo                  1386 non-null   float64
 8   Demo1-3               1386 non-null   float64
 9   Demo4-5               1386 non-null   float64
 10  Natural               1386 non-null   float64
 11  Fitness               1386 non-null   float64
dtypes: datetime64[ns](1), float64(9), object(2)
memory usage: 130.1+ KB